# Default configuration file for Gemini Autonomous Agent
gemini_model: "gemini-2.0-flash-lite"
gemini_temperature: 0.7
gemini_max_tokens: 2048
log_level: "INFO"
health_check_interval: 30
max_concurrent_tasks: 5
